[SDS-941] remove Lisa backend
QuTech-Delft/pennylane-quantuminspire pull request #145
Opened 2024-03-25 15:39 UTC by maxsnoodijk

Removed Lisa backend from integration tests.

2024-03-26 15:17 UTC, QFer requested changes
This is not all.
I see appearances of this backend in the documentation, unit tests.

2024-03-27 14:45 UTC, maxsnoodijk commented
Lisa backend has been removed from documentation and all tests.

2024-04-04 10:40 UTC, QFer commented
Build of docs failed!

2024-04-08 09:44 UTC, QFer approved these changes

2024-04-08 13:39 UTC, merged